### ISSUE TITLE
NERDataHandler Roadmap

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/langtest#2]
## Description

Create a `NERDataHandler` class that establishes a common CoNLL data structure for all libraries to process labeled NER data. This includes:

- Write and read methods
- Storing docs indexes
- Easily filtering
- Converting inputs to match external library requirements (including direct dataset download from HF datasets)

This issue will be used to track the sub-tasks required to launch and maintain this class.

## Tasks

- [x] [Ensure class supports robustness testing/fixing with Spark NLP](https://github.com/JohnSnowLabs/nlptest/issues/12)
- [ ] Ensure class supports bias testing with Spark NLP
- [ ] Ensure class supports noisy label testing/fixing with Spark NLP
- [ ] Ensure class supports robustness testing/fixing with transformers
- [ ] Ensure class supports bias testing with transformers
- [ ] Ensure class supports noisy label testing/fixing with transformers
- [ ] Ensure class supports robustness testing/fixing with spaCy
- [ ] Ensure class supports bias testing with spaCy
- [ ] Ensure class supports noisy label testing/fixing with spaCy
