### ISSUE TITLE
Documentation Roadmap

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/langtest#22]
## Description

This is the roadmap for all things related to knowledge translation and documentation. This includes:

- tutorial notebooks
- readme instructions
- blogposts
- docs

## Tasks

- [x] https://github.com/JohnSnowLabs/nlptest/issues/23
- [ ] https://github.com/JohnSnowLabs/nlptest/issues/24
- [ ] https://github.com/JohnSnowLabs/nlptest/issues/25
- [ ] https://github.com/JohnSnowLabs/nlptest/issues/26
- [ ] https://github.com/JohnSnowLabs/nlptest/issues/27
- [ ] https://github.com/JohnSnowLabs/nlptest/issues/34
