### ISSUE TITLE
NERModelHandler Roadmap

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/langtest#3]
## Description

Create a `NERModelHandler` class that establishes a common way for inference and training on NER models from different libraries. This includes:

- Wrapping NER inference pipelines for Spark NLP, transformers and spaCy
- Standardizing output formats for all pipeline predictions
- Wrapping training process for Spark NLP, transformers and spaCy models

This issue will be used to track the sub-tasks required to launch and maintain this class.

## Tasks

- [ ] [Ensure class supports robustness testing with Spark NLP](https://github.com/JohnSnowLabs/nlptest/issues/13)
- [ ] Ensure class supports bias testing with Spark NLP
- [ ] Ensure class supports noisy label testing/fixing with Spark NLP
- [ ] Ensure class supports robustness testing with transformers
- [ ] Ensure class supports bias testing with transformers
- [ ] Ensure class supports noisy label testing/fixing with transformers
- [ ] Ensure class supports robustness testing with spaCy
- [ ] Ensure class supports bias testing with spaCy
- [ ] Ensure class supports noisy label testing/fixing with spaCy
