### ISSUE TITLE
Robustness Testing Roadmap

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/langtest#4]
## Adaptations

- [x] https://github.com/JohnSnowLabs/nlptest/issues/10
- [ ] https://github.com/JohnSnowLabs/nlptest/issues/11
- [ ] https://github.com/JohnSnowLabs/nlptest/issues/12
- [ ] https://github.com/JohnSnowLabs/nlptest/issues/13
- [ ] Adapt handler classes for robustness testing in transformers
- [ ] Adapt handler classes for robustness testing in spaCy

Colab notebook used to experiment: https://colab.research.google.com/drive/1VkBn3xn0yS1MzxR_w30ONRgZNNDjVByt?usp=sharing

## Improvements

- [ ] https://github.com/JohnSnowLabs/nlptest/issues/16
- [x] https://github.com/JohnSnowLabs/nlptest/issues/28
- [ ] Apply entity swapping to all entities in sentence (instead of 1)
- [ ] Add type checking to main function
- [ ] Supporting classification, assertion, relation extraction tasks

## Bug Fixes

🚀
