### ISSUE TITLE
Features Backlog

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/langtest#46]
## Parked Ideas 🚗 

- [ ] Testing social stereotypes for MLMs ([paper](https://aclanthology.org/2020.emnlp-main.154/))
- [ ] Adding support for cloud provider models to be tested
- [x] Support an installation for airgapped environments
- [ ] Need to generate a spec of what data the model expects and can safely run with (for example, if a model has only been validated on females aged 18 and up, then the model should not be used on people outside that demographic group) - see https://ianwhitestone.work/hello-great-expectations/
- [x] Toxicity tests (swear words, offensive answers)
- [ ] Data leakage tests (PHI)
- [ ] Adversarial attacks tests
- [ ] Freshness tests (replace _2023_name)
- [x] Runtime tests
- [x] Question answering 
- [ ] Text generation
- [x] Summarization
- [ ] Paraphrasing
- [ ] Translation
