### ISSUE TITLE
Robustness Fixing Roadmap

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/langtest#5]
## Adaptations

- [x] https://github.com/JohnSnowLabs/nlptest/issues/10
- [ ] https://github.com/JohnSnowLabs/nlptest/issues/12
- [ ] Adapt NERDataHandler class for robustness fixing in transformers
- [ ] Adapt NERDataHandler class for robustness fixing in spaCy

## Improvements

- [x] https://github.com/JohnSnowLabs/nlptest/issues/19
- [x] https://github.com/JohnSnowLabs/nlptest/issues/29
- [ ] Add optimization algo for all augmentations so that we get 100% augmentation coverage for all tests as much as possible (use similar method to new noise_proportion method in robustness testing -> sample after augmenting all)
- [ ] Track if change occurred in every sentence for every augmentation
- [ ] Apply entity swapping to all entities in sentence (instead of 1)
- [ ] Add type checking to main function
- [ ] Supporting classification, assertion, relation extraction tasks
- [ ] Become compatible with many types of DOCSTART

## Bug Fixes

🎉
