### ISSUE TITLE
Bias Testing Roadmap

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/langtest#6]
## Adaptations

- [ ] Pick and implement final gender classification method
- [ ] Replace NerDLMetrics with sklearn classification_report
- [ ] Adapt handler classes for bias testing in Spark NLP
- [ ] Adapt handler classes for bias testing in transformers
- [ ] Adapt handler classes for bias testing in spaCy

## Improvements

- [ ] https://github.com/JohnSnowLabs/nlptest/issues/30
- [ ] Add type checking to main function
- [ ] Supporting classification, assertion, relation extraction tasks

## Bug Fixes

🎉
