### ISSUE TITLE
Noisy Labels Testing Roadmap

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/langtest#7]
## Adaptations

- [ ] Adapt handler classes for noisy labels testing in Spark NLP
- [ ] Adapt handler classes for noisy labels testing in transformers - [notebook](https://github.com/cleanlab/examples/blob/master/entity_recognition/entity_recognition_training.ipynb)
- [ ] Adapt handler classes for noisy labels testing in spaCy

## Improvements

- [x] https://github.com/JohnSnowLabs/nlptest/issues/20
- [ ] https://github.com/JohnSnowLabs/nlptest/issues/31
- [ ] Improve scoring using sentence label quality score
- [ ] Add type checking to main function
- [ ] Supporting classification, assertion, relation extraction tasks

## Bug Fixes

🎉
