### ISSUE TITLE
Noisy Labels Fixing Roadmap

### ISSUE THREAD

**Issue by luca-martial** [JohnSnowLabs/langtest#8]
## Adaptations

- [ ] Adapt handler classes for noisy labels testing in Spark NLP
- [ ] Adapt handler classes for noisy labels testing in transformers
- [ ] Adapt handler classes for noisy labels testing in spaCy

## Improvements

- [ ] https://github.com/JohnSnowLabs/nlptest/issues/32
- [ ] Prettify UI dropdown, groupby sentences like in ALAB UI
- [ ] Add type checking to main function
- [ ] Supporting classification, assertion, relation extraction tasks

## Bug Fixes

- [ ] Fix UI jupyter lab compatibility
